name       : bustle
version    : 0.8.0
release    : 3
source     :
    - https://hackage.haskell.org/package/bustle-0.8.0/bustle-0.8.0.tar.gz : 2fb3e9d9a97db3cd9a3ce763e86947b642bd7733b46206177a1677f08726573c
license    :
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Draw sequence diagrams of D-Bus traffic
description: |
    Bustle is a better dbus-monitor. It records and draws sequence diagrams of D-Bus activity, showing signal emissions, method calls and their corresponding returns, with timestamps for each individual event and the duration of each method call. This can help you check for unwanted D-Bus traffic, and pinpoint why your D-Bus-based application isn't performing as well as you like. It also provides statistics like signal frequencies and average method call times.
builddeps  :
    - pkgconfig(libpcap)
    - haskell-cabal-install
    - haskell-dbus-devel
    - haskell-gtk3-devel
    - help2man
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %make_install PREFIX=/usr
