name       : bustle
version    : 0.8.0
release    : 5
source     :
    - https://hackage.haskell.org/package/bustle-0.8.0/bustle-0.8.0.tar.gz : 2fb3e9d9a97db3cd9a3ce763e86947b642bd7733b46206177a1677f08726573c
license    :
    - LGPL-2.1-or-later
component  : programming.tools
summary    : Draw sequence diagrams of D-Bus traffic
description: |
    Bustle is a better dbus-monitor. It records and draws sequence diagrams of D-Bus activity, showing signal emissions, method calls and their corresponding returns, with timestamps for each individual event and the duration of each method call. This can help you check for unwanted D-Bus traffic, and pinpoint why your D-Bus-based application isn't performing as well as you like. It also provides statistics like signal frequencies and average method call times.
builddeps  :
    - pkgconfig(libpcap)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pango)
    - pkgconfig(cairo)
    - ghc-devel
    - haskell-cabal-install
    - help2man
networking : yes
setup      : |
    %patch -p1 < $pkgfiles/bustle_fix_pcap_config_call.patch
    cabal update
    cabal install %JOBS% \
                  alex happy
    export GTK3_VER=gtk3-0.15.5
    cabal unpack $GTK3_VER
    pushd $GTK3_VER
    sed -i "s|@G_SEARCHPATH_SEPARATOR_S@||" Graphics/UI/Gtk/General/RcStyle.chs
    %patch -p1 < $pkgfiles/gtk3_levelbar.patch
    cabal install %JOBS% \
                  --ghc-options="-O2 -fPIC"
    popd
    cabal install %JOBS% \
                  --dependencies-only \
                  --ghc-options="-O2 -fPIC"
    cabal configure \
                  --prefix=%PREFIX% \
                  --libdir=%libdir% \
                  --libsubdir="\$compiler/\$pkgid" \
                  --sysconfdir=/etc \
                  --ghc-options="-O2 -fPIC" \
                  --disable-library-for-ghci \
                  --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %make_install PREFIX=/usr
